FROM ubuntu:latest
#RUN apk add --no-cache wget tar sudo
RUN apt-get update && apt-get install -y wget tar sudo
RUN wget -O dxlAPRS.tgz http://dxlaprs.hamspirit.at/dxlAPRS_x86_64-current.tgz
RUN tar xzvf dxlAPRS.tgz --strip=1 scripts/updateDXLaprs
RUN ./updateDXLaprs dxlAPRS.tgz
RUN rm dxlAPRS.tgz && mv /root/dxlAPRS/* /opt/
ENV PATH="/opt/aprs:${PATH}"
RUN which sdrtst
RUN sudo sdrtst
#ENTRYPOINT ["afskmodem", "-e", "-v", "-k"]
#CMD ["-f", "16000", "-M", "0", "-c", "0", "-L", "127.0.0.1:9001:0", "-M", "1", "-c", "1", "-L", "127.0.0.1:9002:0"]
CMD afskmodem
